force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Funding_Mechanism__c</fullName>
        <description>The Funding Meachanism at the Account level indicates how the Groups included within it are being rated, or another key value that determines how they should be managed.  Dependent on the Funding Type field.</description>
        <inlineHelpText>Funding Mechanism values are based upon the Funding Type field selection.</inlineHelpText>
        <label>Funding Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Funding_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Funding_Mechanism</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>Dependent on Funding Mechanism</description>
        <inlineHelpText>Funding Type based on the medical plan.</inlineHelpText>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Funding_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Group__c.object
<CustomObject>
    <description>The Billing Group represents the record/Number that Members and Plans are tied to in CAPS.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>A lookup to an Account record of type Prospect or Customer</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Groups can only be associated to a Customer or Prospect type Account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Groups</relationshipLabel>
        <relationshipName>Billing_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Billing Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Group__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <inlineHelpText>Stores the date the current Plan offered to the Group became (will become) active.</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Group_Opp_Product__c.object
<CustomObject>
    <description>Junction object to support a many-to-many relationship between Opportunity Products and Billing Groups.</description>
    <fields>
        <fullName>Billing_Group__c</fullName>
        <label>Group Name</label>
        <referenceTo>Billing_Group__c</referenceTo>
        <relationshipLabel>Billing Group Opp Products</relationshipLabel>
        <relationshipName>Billing_Group_Opp_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Billing Groups</relationshipLabel>
        <relationshipName>Billing_Group_Opp_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Group Opp Product</label>
    <nameField>
        <displayFormat>BGOP-{00000}</displayFormat>
        <label>Billing Group Opp Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Group Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>The date that the products on this Opportunity will go into effect.  The Renewal Month will be derived from the month of this field.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <inlineHelpText>Contract End Date</inlineHelpText>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Mechanism__c</fullName>
        <description>The Funding Meachanism at the Account level indicates how the Groups included within it are being rated, or another key value that determines how they should be managed. Dependent on the Funding Type field. This field is defaulted to the values on the Account record.</description>
        <inlineHelpText>This field is originally defaulted to the Funding Mechanism on the Account record. Adjust if needed.</inlineHelpText>
        <label>Funding Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Funding_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Funding_Mechanism</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>Dependent on Funding Mechanism</description>
        <inlineHelpText>This field is originally defaulted to the Funding Type on the Account record. Adjust if needed.</inlineHelpText>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Funding_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Funding_Mechanism.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrative Services Only (ASO)</fullName>
    </customValue>
    <customValue>
        <fullName>Alternative Financial Method (AFM)</fullName>
    </customValue>
    <customValue>
        <fullName>Community Rated Group (CRG)</fullName>
    </customValue>
    <customValue>
        <fullName>Merit Rated Group (MRG)</fullName>
    </customValue>
    <customValue>
        <fullName>Retro</fullName>
    </customValue>
    <customValue>
        <fullName>EUTF</fullName>
    </customValue>
    <customValue>
        <fullName>Fed</fullName>
    </customValue>
    <description>The Funding Mechanism at the Account level indicates how the Groups included within it are being rated, or another key value that determines how they should be managed.</description>
    <masterLabel>Funding Mechanism</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Funding_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fully Insured</fullName>
    </customValue>
    <customValue>
        <fullName>Self Insured</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <masterLabel>Funding Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTriggerTest.cls
/*****************************************************************
Name:  OpportunityTriggerTest
 
=================================================================
Purpose: 
Unit Test methods for Opportunity triggers                                                                                                                       
=================================================================
History                                                            
-------                                                            
VERSION  AUTHOR         DATE           DETAIL          Description
1.0   	 aashiru        06/2018        Created         AMS:
*****************************************************************/

@isTest
private class OpportunityTriggerTest {
	
	@isTest static void testAcceptanceOppsWithoutBillingGroup() {
        User testUser = TestDataFactory.getTestUser();
        System.runAs(testUser) {
			TestDataFactory.setupProposalAcceptanceOpps();
        
        	Test.startTest();

        	List<Opportunity> oppList = [Select Id, StageName, Effective_End_Date__c From Opportunity];
        	for(Opportunity opp : oppList) {
                opp.Effective_Date__c=Date.today();
                opp.Funding_Type__c='Fully Insured';
                opp.Funding_Mechanism__c='Community Rated Group (CRG)';
        		opp.StageName = 'Post Proposal Acceptance';
        	}
        	update oppList;

        	Test.stopTest();

        	// Assert Billing Groups were created
        	List<Account> accList = [Select Id, Name From Account];
        	System.assert([SELECT COUNT() from Billing_Group__c Where Account__c = :accList[0].Id] == 1);

        	// Assert Billing Group Opportunity Products were created
        	System.assert([SELECT COUNT() from Billing_Group_Opp_Product__c Where Opportunity__c = :oppList[0].Id] == 1);	
        }
	}
    
    @isTest static void testAcceptanceOppsWithExistingBillingGroup() {
        User testUser = TestDataFactory.getTestUser();
        System.runAs(testUser) {
			TestDataFactory.setupAcceptanceOppsWithBillingGroup();
        
        	Test.startTest();

        	List<Opportunity> oppList = [Select Id, StageName, Effective_End_Date__c From Opportunity];
        	for(Opportunity opp : oppList) {
                opp.Effective_Date__c=Date.today();
                opp.Funding_Type__c='Fully Insured';
                opp.Funding_Mechanism__c='Community Rated Group (CRG)';
        		opp.StageName = 'Post Proposal Acceptance';
        	}
        	update oppList;

        	Test.stopTest();
            
            // Assert New Billing Group were not created
        	System.assert([SELECT COUNT() from Billing_Group__c] == 5);	

        	// Assert Billing Group Opportunity Products were created
        	System.assert([SELECT COUNT() from Billing_Group_Opp_Product__c Where Opportunity__c = :oppList[0].Id] == 1);	
        }
	}
    
    @isTest static void testOpportunityValidationWithMissingData() {
        User testUser = TestDataFactory.getTestUser();
        System.runAs(testUser) {

        	Test.startTest();
            try {
            	TestDataFactory.setupOpportunityWithMissingData('New');
        	
            	List<Opportunity> oppList = [Select Id, StageName From Opportunity];
        		for(Opportunity opp : oppList) {
        			opp.StageName='Closed Won';
        		}
        		update oppList;
                
                // We don't expect to get here as the insert should fail
            	System.Assert (false);
            }
			catch (DMLException e) {
            	// We expect the insert to fail
            	System.Assert (true);
        	}
        	Test.stopTest();	
        }
	}
    
    @isTest static void testOpportunityValidationWithCompleteData() {
        User testUser = TestDataFactory.getTestUser();
        
        System.runAs(testUser) {

        	Test.startTest();

            TestDataFactory.setupOpportunityWithCompleteData('New');
        		
            List<Opportunity> oppList = [Select Id, StageName From Opportunity];
            for(Opportunity opp : oppList) {
        		opp.StageName='Closed Won';
        	}
        	update oppList;
                
           	System.AssertEquals (true, OpportunityTriggerHelper.OpportunityValidator(oppList[0], null));
           	System.Assert(true);
            
            Test.stopTest();	
        }
        
	}
	
}