force-app/main/default/objects/AMS_App_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Months_Post_Rating_Class__c</fullName>
        <defaultValue>&quot;7&quot;</defaultValue>
        <label>Months Post Rating Class</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>AMS App Config</label>
</CustomObject>

force-app/main/default/objects/Billing_Group__c.object
<CustomObject>
    <description>The Billing Group represents the record/Number that Members and Plans are tied to in CAPS.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>A lookup to an Account record of type Prospect or Customer</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Groups can only be associated to a Customer or Prospect type Account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Groups</relationshipLabel>
        <relationshipName>Billing_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Agent_Code__c</fullName>
        <inlineHelpText>A legacy value that roughly corresponds to the Customer account, but doesn&apos;t always.  Should be defined by Underwriting.</inlineHelpText>
        <label>Agent Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Status__c</fullName>
        <defaultValue>&apos;Pending&apos;</defaultValue>
        <inlineHelpText>This shows the status of the Group from CAPS data.</inlineHelpText>
        <label>Group Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating_Class__c</fullName>
        <inlineHelpText>Select the month that renewal rating should be initiated.  Affects the Experience Period, Data Pull Date and Delivered to SAM Date.</inlineHelpText>
        <label>Rating Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <label>Billing Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Group__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <inlineHelpText>Stores the date the current Plan offered to the Group became (will become) active.</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>The date that the products on this Opportunity will go into effect.  The Renewal Month will be derived from the month of this field.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Member_Percent__c</fullName>
        <description>Allows the user to indicate what percentage of people they think will choose the plan that is being offered, by applying this value to the Employee Count or the Member Count.</description>
        <label>Expected Member %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Initiating_Billing_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Billing Group that has prompted the creation of this Opportunity.</inlineHelpText>
        <label>Initiating Billing Group</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Billing Group must be on the same Account as the Opportunity.</errorMessage>
            <filterItems>
                <field>Billing_Group__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Billing_Group__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>AMS Global</businessProcess>
        <description>For Opportunities to renew a Customer for the following year.</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityRenewalOfRatingClassBatch.cls
/*****************************************************************
Name:  OpportunityRenewalOfRatingClassBatch
 
=================================================================
Purpose: 
Apex batch process for auto renewal Opportunities based on 
specified rating class controlled by custom settings.
=================================================================
History                                                            
-------                                                            
VERSION  AUTHOR         DATE           DETAIL          Description
1.0   	 aashiru        06/2018        Created         AMS:
*****************************************************************/

global class OpportunityRenewalOfRatingClassBatch implements Database.Batchable<sObject> {
	
	String query;
    private final String appConfig;  
    private final String oppRecTypeId;
	
	global OpportunityRenewalOfRatingClassBatch() {
		 // Get App Config custom settings
    	this.appConfig = AMS_App_Config__c.getOrgDefaults().Months_Post_Rating_Class__c;
        
        // Get Record Type ID
        this.oppRecTypeId = Schema.getGlobalDescribe()
        	.get('Opportunity').getDescribe()
        	.getRecordTypeInfosByName()
        	.get('Renewal')
        	.getRecordTypeId();
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {

		query = 'SELECT Id, Account__c, Account__r.Name, Account__r.OwnerId, ' +
                        'Rating_Class__c, Renewal_Date__c, Agent_Code__c ' +
                        'FROM Billing_Group__c ' +
                        'WHERE Rating_Class__c != Null ' +
                        'AND Renewal_Date__c != Null ' +
                        'AND (Group_Status__c = \'Active\' ' +
                        'OR Group_Status__c = \'Pending\')';
        
		return Database.getQueryLocator(query);
	}

  	global void execute(Database.BatchableContext BC, List<Billing_Group__c> groups) {	

   		List<Billing_Group__c> groupsForRenewal = new List<Billing_Group__c>();
     
 		// Iterate and assemble groups that are 7 months prior to rating class 
   		for (Billing_Group__c iterGroup : groups) {
            String monthsPriorRatingClass = !Test.isRunningTest() ? this.appConfig : '7';
          	if(OpportunityRenewalHelper.getDateRenewalRatingClass(
                                            iterGroup.Rating_Class__c,
                                            iterGroup.Renewal_Date__c.year()).month() == Date.today().addMonths(Integer.valueof(monthsPriorRatingClass)).month()) {
   				groupsForRenewal.add(iterGroup);
   			}
   		}
   		List<Opportunity> opps = new List<Opportunity>();
   		
      	Set<String> qualifyAccountsForRenewal = new Set<String>();
      	for (Billing_Group__c iterGroup2 : groupsForRenewal) {
        	qualifyAccountsForRenewal.add(iterGroup2.Account__c);
      	}

      	Map<Id, List<Opportunity>> renewalOppMap = new  Map<Id, List<Opportunity>>();
      	for(Opportunity opp : [Select Id, RecordTypeId, CloseDate, StageName, AccountId, OwnerId From Opportunity Where 
                              RecordTypeId = :oppRecTypeId And AccountId IN :qualifyAccountsForRenewal]) {
        	List<Opportunity> oppList = renewalOppMap.get(opp.AccountId) != null ? 
                                      renewalOppMap.get(opp.AccountId) : new List<Opportunity>();
        	oppList.add(opp);
        	renewalOppMap.put(opp.AccountId, oppList);
      	}
        
      	Set<String> accountForRenewal = new Set<String>();
      	Map<Id, List<Billing_Group__c>> dupRatingClassMap = new Map<Id, List<Billing_Group__c>>(); 
        List<Billing_Group__c> dupGroupList;
        integer counter = 1;   
   		for (Billing_Group__c iterGroup2 : groupsForRenewal) {
        	Boolean dupRatingClassExists = false;    
            if(counter == 1) {
                dupGroupList = new List<Billing_Group__c>();
                dupGroupList.add(iterGroup2);
                dupRatingClassMap.put(iterGroup2.Account__c, dupGroupList);
          	}
          	else {
            	dupGroupList = dupRatingClassMap.get(iterGroup2.Account__c); 
                if(dupGroupList != null) {
                	for(Billing_Group__c grp : dupGroupList) {
               			if(grp.Rating_Class__c == iterGroup2.Rating_Class__c) {
            				dupRatingClassExists = true;
                    	}
                 	}
                    if(dupRatingClassExists) {
                		dupGroupList.add(iterGroup2);
                		dupRatingClassMap.put(iterGroup2.Account__c, dupGroupList);
          				continue;
        			} 
                }
                else {
                    dupGroupList = new List<Billing_Group__c>();
                    dupGroupList.add(iterGroup2);
                	dupRatingClassMap.put(iterGroup2.Account__c, dupGroupList);
                }
          	}
            counter++; 
            if(dupRatingClassExists) {
          		continue;
        	} 
         
        	List<Opportunity> oppList2 = renewalOppMap.get(iterGroup2.Account__c);
        	Boolean renewalOppExists = false;
        	if(oppList2 != null && !oppList2.isEmpty()) {
          		for(Opportunity opp2 : oppList2) {
            		if((opp2.CloseDate == iterGroup2.Renewal_Date__c && opp2.OwnerId == iterGroup2.Account__r.OwnerId)
                  		|| (opp2.StageName != 'Closed Won' && opp2.StageName != 'Closed Lost')) {
              			renewalOppExists = true;
            		}
          		}
        	}
        	if(oppList2 == null || !renewalOppExists) {
          		accountForRenewal.add(iterGroup2.Account__c);

          		Opportunity opp = new Opportunity(Name='Renewal for '+ iterGroup2.Account__r.Name, 
                                             CloseDate=iterGroup2.Renewal_Date__c,
                                             Effective_Date__c=iterGroup2.Renewal_Date__c,
                                             RecordTypeId=oppRecTypeId, 
                                             Expected_Member_Percent__c=100,
                                             OwnerId=iterGroup2.Account__r.OwnerId,
                                             AccountId=iterGroup2.Account__c,
                                             Initiating_Billing_Group__c=iterGroup2.Id,      
                                             StageName='Planning');
          		opps.add(opp); 
        	}
      	}
        
        //Determine earliest renewal date 
        for(Opportunity op : opps) {
            List<Billing_Group__c> renGroupList = dupRatingClassMap.get(op.AccountId);
            if(renGroupList != Null && renGroupList.size() > 1) {
                // Sort group list
            	OpportunityRenewalHelper[] renewalGroupList = new List<OpportunityRenewalHelper>();
            	for (Billing_Group__c renGroup : renGroupList) {
              		renewalGroupList.add(new OpportunityRenewalHelper(renGroup));
            	}
            	renewalGroupList.sort();
            	op.Effective_Date__c = renewalGroupList[0].billGroup.Renewal_Date__c;
              op.CloseDate = renewalGroupList[0].billGroup.Renewal_Date__c;
            }  
        }
      	
        // Create Opportunity Products
      	OpportunityRenewalHelper.createOpportunityProducts(groupsForRenewal, opps, accountForRenewal);
	
	}
	
	global void finish(Database.BatchableContext BC) {
	}
	
}