force-app/main/default/objects/AMS_App_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Days_Before_Oppty_Renewal__c</fullName>
        <defaultValue>&quot;60&quot;</defaultValue>
        <label>Days Before Oppty Renewal</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>AMS App Config</label>
</CustomObject>

force-app/main/default/objects/Billing_Group__c.object
<CustomObject>
    <description>The Billing Group represents the record/Number that Members and Plans are tied to in CAPS.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>A lookup to an Account record of type Prospect or Customer</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Groups can only be associated to a Customer or Prospect type Account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Groups</relationshipLabel>
        <relationshipName>Billing_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Agent_Code__c</fullName>
        <inlineHelpText>A legacy value that roughly corresponds to the Customer account, but doesn&apos;t always.  Should be defined by Underwriting.</inlineHelpText>
        <label>Agent Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating_Class__c</fullName>
        <inlineHelpText>Select the month that renewal rating should be initiated.  Affects the Experience Period, Data Pull Date and Delivered to SAM Date.</inlineHelpText>
        <label>Rating Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <label>Billing Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Expected_Member_Percent__c</fullName>
        <description>Allows the user to indicate what percentage of people they think will choose the plan that is being offered, by applying this value to the Employee Count or the Member Count.</description>
        <label>Expected Member %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>AMS Global</businessProcess>
        <description>For Opportunities to renew a Customer for the following year.</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityRenewalBatch.cls
global class OpportunityRenewalBatch implements 
	Database.Batchable<sObject> {
        
    String query;
    private final String appConfig;  
    private final String oppRecTypeId;
        
    global OpportunityRenewalBatch() {
        // Get App Config custom settings
    	this.appConfig = AMS_App_Config__c.getOrgDefaults().Days_Before_Oppty_Renewal__c;
        
        // Get Record Type ID
        this.oppRecTypeId = Schema.getGlobalDescribe()
        	.get('Opportunity').getDescribe()
        	.getRecordTypeInfosByName()
        	.get('Assumptive Renewal')
        	.getRecordTypeId();
  	}
          
    global Database.QueryLocator start(Database.BatchableContext bc) {        
      System.debug('###appConfig: '+appConfig);
        
      // collect the batches of records to be passed to execute
      // Select all Billing Groups due for renewal in 60 days
      query = 'SELECT Id, Account__c, Account__r.Name, Account__r.OwnerId, ' +
                        'Rating_Class__c, Renewal_Date__c, Agent_Code__c ' +
                        'FROM Billing_Group__c ' +
            			      'WHERE Renewal_Date__c = NEXT_N_DAYS:' + this.appConfig + 
                        ' AND Agent_Code__c IN (\'C000\', \'C900\')';
        
      System.debug('###SOQL: '+query);
        
      return Database.getQueryLocator(query);
    }
    
 	  global void execute(Database.BatchableContext bc, List<Billing_Group__c> groups){
        
      System.debug('###Billing Groups: '+groups);
        
      // process each batch of records, populate Set with the Group's Ids
      List<Opportunity> assRenewalOpps = new List<Opportunity>();
      Set<String> accountIds = new Set<String>();
      List<Billing_Group__c> assRenewalGroups = new List<Billing_Group__c>();
       
      for (Billing_Group__c iterGroup : groups) {
          Date renewalDate = iterGroup.Renewal_Date__c;
          if(renewalDate.isSameDay(Date.today().addDays(Integer.valueOf(this.appConfig)))) {
              accountIds.add(iterGroup.Account__c);
              assRenewalGroups.add(iterGroup);
              Opportunity opp = new Opportunity(Name='Assumptive Renewal for '+ iterGroup.Account__r.Name, 
                                             CloseDate=Date.today().addDays(30),
                                             RecordTypeId=oppRecTypeId,
                                             Expected_Member_Percent__c=100,
                                             OwnerId=iterGroup.Account__r.OwnerId,
                                             AccountId=iterGroup.Account__c,
                                             StageName='New');
          assRenewalOpps.add(opp); 
        }
      }
      System.debug('###Renewal Opportunities: '+assRenewalOpps);

      // Create Opportunity Products
      if(!assRenewalGroups.isEmpty() && !assRenewalOpps.isEmpty()) {
        OpportunityRenewalHelper.createOpportunityProducts(assRenewalGroups, assRenewalOpps, accountIds);
      }
    }   
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }    
}