force-app/main/default/objects/AMS_App_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Days_Post_Oppty_Renewal__c</fullName>
        <defaultValue>&quot;30&quot;</defaultValue>
        <label>Days Post Oppty Renewal</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>AMS App Config</label>
</CustomObject>

force-app/main/default/objects/Billing_Group__c.object
<CustomObject>
    <description>The Billing Group represents the record/Number that Members and Plans are tied to in CAPS.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>A lookup to an Account record of type Prospect or Customer</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Groups can only be associated to a Customer or Prospect type Account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Groups</relationshipLabel>
        <relationshipName>Billing_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Agent_Code__c</fullName>
        <inlineHelpText>A legacy value that roughly corresponds to the Customer account, but doesn&apos;t always.  Should be defined by Underwriting.</inlineHelpText>
        <label>Agent Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <label>Billing Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>AMS Global</businessProcess>
        <description>For Opportunities to renew a Customer for the following year.</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityRenewalClosedBatch.cls
global class OpportunityRenewalClosedBatch implements Database.Batchable<sObject> {
    
    String query;
    List<String> errors;
    private final String appConfig;  
    private final String oppRecTypeId;
    
    global OpportunityRenewalClosedBatch() {
          // Get App Config custom settings
        this.appConfig = AMS_App_Config__c.getOrgDefaults().Days_Post_Oppty_Renewal__c;
        
        // Get Record Type ID
        this.oppRecTypeId = Schema.getGlobalDescribe()
            .get('Opportunity').getDescribe()
            .getRecordTypeInfosByName()
            .get('Assumptive Renewal')
            .getRecordTypeId();
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        // collect the batches of records to be passed to execute
        // Select all Billing Groups due for renewal in 60 days
        query = 'SELECT Id, Account__c, Renewal_Date__c, Agent_Code__c ' +
                'FROM Billing_Group__c ' +
                'WHERE Renewal_Date__c = NEXT_N_DAYS:' + this.appConfig + 
                ' AND Agent_Code__c IN (\'C000\', \'C900\')';

        System.debug('###SOQL: '+query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Billing_Group__c> groups) {

        errors = new List<String>(); 
        Set<String> accountIds = new Set<String>();
        for (Billing_Group__c iterGroup : groups) {
            accountIds.add(iterGroup.Account__c);
        }
        if(!accountIds.IsEmpty()) {
            List<Opportunity> opps = [SELECT Id, Name, AccountId, StageName, RecordType.Name FROM Opportunity];
            System.debug('###Opps: '+opps);
            System.debug('###RecordType Name: '+opps[0].RecordType.Name);
            System.debug('###oppRecTypeId: '+oppRecTypeId);
            System.debug('###accountIds: '+accountIds);

            List<Opportunity> oppList = [SELECT Id, Name, AccountId, StageName, RecordTypeId 
                                            FROM Opportunity 
                                            WHERE StageName <> 'Closed Won'
                                            AND RecordType.Name = : 'Assumptive Renewal'
                                            AND AccountId IN : accountIds];

            System.debug('###oppList: '+oppList);
            if(oppList != null && !oppList.isEmpty()) {

                for(Opportunity opp : oppList) {
                    opp.StageName = 'Closed Won';
                }
                // Create a Save Point to rollback the DML operations if needed
                Savepoint sp = Database.setSavepoint();
                
                try{
                    List<Database.SaveResult> srList = Database.update(oppList, false);
                    for (Database.SaveResult sr : srList) {
                        if (!sr.isSuccess()) {
                            // Operation failed, so get all errors               
                            for(Database.Error err : sr.getErrors()) {
                            errors.add('The following error has occurred. ' + 
                                err.getStatusCode() + ': ' + 
                                err.getMessage() + ' : Fields that affected this error: ' + 
                                err.getFields());
                            }
                        }
                    }
                }
                catch (DMLException e) {
                    errors.add('Error: ' + e.getMessage() + '; Stack Trace: ' + e.getStackTraceString());
                    System.debug('Error: ' + e.getMessage() + '; Stack Trace: ' + e.getStackTraceString());
            
                    // Rollback, upsert operation failed
                    Database.rollback(sp);
                }
                if(!errors.IsEmpty()) {
                    System.debug('###Errors: '+errors);
                }
            }                               

        }
    
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
    
}