force-app/main/default/objects/AMS_App_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Days_Before_Oppty_Renewal__c</fullName>
        <defaultValue>&quot;60&quot;</defaultValue>
        <label>Days Before Oppty Renewal</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days_Post_Oppty_Renewal__c</fullName>
        <defaultValue>&quot;30&quot;</defaultValue>
        <label>Days Post Oppty Renewal</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Months_Post_Rating_Class__c</fullName>
        <defaultValue>&quot;7&quot;</defaultValue>
        <label>Months Post Rating Class</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>AMS App Config</label>
</CustomObject>

force-app/main/default/objects/Billing_Group__c.object
<CustomObject>
    <description>The Billing Group represents the record/Number that Members and Plans are tied to in CAPS.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>A lookup to an Account record of type Prospect or Customer</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Groups can only be associated to a Customer or Prospect type Account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Groups</relationshipLabel>
        <relationshipName>Billing_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Agent_Code__c</fullName>
        <inlineHelpText>A legacy value that roughly corresponds to the Customer account, but doesn&apos;t always.  Should be defined by Underwriting.</inlineHelpText>
        <label>Agent Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating_Class__c</fullName>
        <inlineHelpText>Select the month that renewal rating should be initiated.  Affects the Experience Period, Data Pull Date and Delivered to SAM Date.</inlineHelpText>
        <label>Rating Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <label>Billing Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Group__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <inlineHelpText>Stores the date the current Plan offered to the Group became (will become) active.</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Group_Opp_Product__c.object
<CustomObject>
    <description>Junction object to support a many-to-many relationship between Opportunity Products and Billing Groups.</description>
    <fields>
        <fullName>Billing_Group__c</fullName>
        <label>Group Name</label>
        <referenceTo>Billing_Group__c</referenceTo>
        <relationshipLabel>Billing Group Opp Products</relationshipLabel>
        <relationshipName>Billing_Group_Opp_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Billing Group Opp Product</label>
    <nameField>
        <displayFormat>BGOP-{00000}</displayFormat>
        <label>Billing Group Opp Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Group Opp Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Product__c.object
<CustomObject>
    <description>Read Only object to store actual plan / rate data from CAPS so it can easily be seen and reported on in Salesforce.</description>
    <fields>
        <fullName>Billing_Group__c</fullName>
        <label>Billing Group</label>
        <referenceTo>Billing_Group__c</referenceTo>
        <relationshipLabel>Billing Products</relationshipLabel>
        <relationshipName>Billing_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Drug_Coverage_Code__c</fullName>
        <label>Drug Coverage Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Med_Coverage_Code__c</fullName>
        <label>Med Coverage Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Billing Products</relationshipLabel>
        <relationshipName>Billing_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Coverage_Code__c</fullName>
        <label>Vision Coverage Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Billing Product</label>
    <nameField>
        <label>Billing Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Code__c.object
<CustomObject>
    <description>This object stores records that will be used in the auto-renewal opportunity creation process.</description>
    <fields>
        <fullName>Active_Through__c</fullName>
        <inlineHelpText>Enter the date through which the new cov code should be used.  E.g. 7/31/2018 to include the last day of July.  This will be compared against the expected renewal date.  Leave blank if there is no end date.</inlineHelpText>
        <label>Active Through</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Coverage_Code_Type__c</fullName>
        <inlineHelpText>Pick the Coverage Code type this &quot;replacement&quot; will apply to.</inlineHelpText>
        <label>Coverage Code Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Coverage_Code_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Cov_Code__c</fullName>
        <inlineHelpText>Enter the Cov Code you want to be replaced.</inlineHelpText>
        <label>Current Cov Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Cov_Code__c</fullName>
        <inlineHelpText>Enter the Cov Code value to be used going forward.</inlineHelpText>
        <label>New Cov Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Enter the date the new cov code should start being used.  This will be compared against the expected renewal date.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Coverage Code</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Cov Code ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <inlineHelpText>Select the Type(s) of Fully Insured contracts or documents that need to be prepared for this Opportunity.</inlineHelpText>
        <label>Contract Type(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Evergreen</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Multi-Year</fullName>
                </value>
                <value>
                    <fullName>Contingent</fullName>
                </value>
                <value>
                    <fullName>Reverse Contingent</fullName>
                </value>
                <value>
                    <fullName>Rider Only</fullName>
                </value>
                <value>
                    <fullName>Modified / Amendment</fullName>
                </value>
                <value>
                    <fullName>Exhibits Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>The date that the products on this Opportunity will go into effect.  The Renewal Month will be derived from the month of this field.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Member_Percent__c</fullName>
        <description>Allows the user to indicate what percentage of people they think will choose the plan that is being offered, by applying this value to the Employee Count or the Member Count.</description>
        <label>Expected Member %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Jeopardy_Status__c</fullName>
        <inlineHelpText>If this Opportunity is in jeopardy, select a reason. This information is used for reporting and sales planning.</inlineHelpText>
        <label>Jeopardy Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not in Jeopardy</fullName>
                    <default>true</default>
                    <label>Not in Jeopardy</label>
                </value>
                <value>
                    <fullName>Risk of Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Closed Business</fullName>
                </value>
                <value>
                    <fullName>Data Reporting</fullName>
                </value>
                <value>
                    <fullName>Market_Study</fullName>
                    <label>Market Study</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Plan Consolidation / Ease of Admin</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                    <isActive>false</isActive>
                    <label>Competition</label>
                </value>
                <value>
                    <fullName>Shopping</fullName>
                    <isActive>false</isActive>
                    <label>Shopping</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Benefit_info_with_confirmation__c</fullName>
        <inlineHelpText>Select to indicate if you have included the needed information or not.</inlineHelpText>
        <label>Rate &amp; Benefit info with confirmation?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>AMS Global</businessProcess>
        <description>For Opportunities to renew a Customer for the following year.</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Billing_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Group</label>
        <referenceTo>Billing_Group__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Drug_Coverage_Code__c</fullName>
        <label>Drug Cov Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Med_Coverage_Code__c</fullName>
        <label>Med Cov Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Coverage_Code__c</fullName>
        <label>Vision Cov Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/Coverage_Code_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ancillary Cov Code</fullName>
    </customValue>
    <customValue>
        <fullName>Dental Cov Code</fullName>
    </customValue>
    <customValue>
        <fullName>Drug Cov Code</fullName>
    </customValue>
    <customValue>
        <fullName>Med Cov Code</fullName>
    </customValue>
    <customValue>
        <fullName>Vision Cov Code</fullName>
    </customValue>
    <masterLabel>Coverage Code Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Yes_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>Yes No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
/*****************************************************************
Name:  TestDataFactory
 
=================================================================
Purpose: 
Common unit test suites
=================================================================
History                                                            
-------                                                            
VERSION  AUTHOR         DATE           DETAIL          Description
1.0   	 aashiru        06/2018        Created         AMS:
*****************************************************************/

@isTest
public class TestDataFactory implements HttpCalloutMock {

    static List<Account> accounts; 
    static List<Contact> contacts; 
    static List<Billing_Group__c> groups; 
    static List<Billing_Product__c> products;
    static List<Opportunity> opps;  
    static List<OpportunityLineItem> oppProducts; 
    static List<Billing_Group_Opp_Product__c> grpOppProducts; 
    static Product2 product;

    static String oppRecTypeId = Schema.getGlobalDescribe()
                                        .get('Opportunity').getDescribe()
                                        .getRecordTypeInfosByName()
                                        .get('Assumptive Renewal')
                                        .getRecordTypeId();

    static String oppRenewalTypeId = Schema.getGlobalDescribe()
                                            .get('Opportunity').getDescribe()
                                            .getRecordTypeInfosByName()
                                            .get('Renewal')
                                            .getRecordTypeId();
        
    static String prospectRecTypeId = Schema.getGlobalDescribe()
                                            .get('Account').getDescribe()
                                            .getRecordTypeInfosByName()
                                            .get('Prospect')
                                            .getRecordTypeId();

    static Id customerRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
                                                            .get('Customer')
                                                            .getRecordTypeId();  


    static public HTTPResponse respond(HTTPRequest req) {
        HttpResponse res = new HttpResponse();
        return res;
    }
    
    public static void setupCommon() {

        product = new Product2(Name='Test', ProductCode='BPE');
        insert product;

        insert new PriceBookEntry(UnitPrice = 100,
                                    PriceBook2Id = Test.getStandardPricebookId(),
                                    Product2Id = product.Id,
                                    IsActive = true);

        insert new AMS_App_Config__c(Days_Before_Oppty_Renewal__c='60',
                                    Days_Post_Oppty_Renewal__c='30',
                                    Months_Post_Rating_Class__c='7');
		
        List<Coverage_Code__c> covCodes = new List<Coverage_Code__c>();
        covCodes.add(new Coverage_Code__c(Coverage_Code_Type__c='Med Cov Code', 
                                    Current_Cov_Code__c='008', 
                                    New_Cov_Code__c='005',
                                    Start_Date__c=Date.today(), 
                                    Active_Through__c=Date.today().addMonths(12)));
         covCodes.add(new Coverage_Code__c(Coverage_Code_Type__c='Drug Cov Code', 
                                    Current_Cov_Code__c='008', 
                                    New_Cov_Code__c='001',
                                    Start_Date__c=Date.today(), 
                                    Active_Through__c=Date.today().addMonths(12)));
        insert covCodes;
        
    }

    
    //@testSetup 
    public static void setup() {

        setupCommon();

        accounts = new List<Account>();
        groups = new List<Billing_Group__c>();
        products = new List<Billing_Product__c>();
        
        for (Integer i=0;i<5;i++) {
            accounts.add(new Account(name='Account '+i, 
                billingcity='New York', billingcountry='USA',
                RecordTypeId=prospectRecTypeId));
        }
        insert accounts;
        
        // find the account just inserted. Add billing group and billing product for each
        for (Account account : [select id from account]) {
            groups.add(new Billing_Group__c(Rating_Class__c='June', 
                Renewal_Date__c=Date.today().addDays(60), 
                account__c=account.id, Agent_Code__c='C000'));
        }
        insert groups;

        for (Billing_Group__c grp : [select id, account__c from Billing_Group__c]) {
            products.add(new Billing_Product__c(name='Test', 
                                                Billing_Group__c =  grp.Id,
                                                Product__c=product.Id,
                                                Drug_Coverage_Code__c='008',
                                                Med_Coverage_Code__c='008',
                                                Vision_Coverage_Code__c='007'));
        }
        insert products;
    }

    public static void setupOpps() {

        setupCommon();

        accounts = new List<Account>();
        groups = new List<Billing_Group__c>();
        opps = new  List<Opportunity>();

        for (Integer i=0;i<5;i++) {
            accounts.add(new Account(name='Account '+i, 
                billingcity='New York', billingcountry='USA',
                RecordTypeId=prospectRecTypeId));
        }
        insert accounts;

        // find the account just inserted. Add billing group for each
        for (Account account : [select id from account]) {
            groups.add(new Billing_Group__c(Rating_Class__c='June', 
                Renewal_Date__c=Date.today().addDays(30), 
                account__c=account.id, Agent_Code__c='C000'));
        }
        insert groups;

        for (Account account : [select Id, Name from account]) {
            opps.add(new Opportunity(Name='Assumptive Renewal for '+ account.Name, 
                                    CloseDate=Date.today().addDays(30),
                                    Effective_Date__c=Date.today().addDays(30),
                                    RecordTypeId=oppRecTypeId,
                                    Expected_Member_Percent__c=100,
                                    AccountId=account.Id,
                                    Rate_Benefit_info_with_confirmation__c='N/A',
                                    Contract_Type__c='Evergreen',
                                    Jeopardy_Status__c='Not in Jeopardy',
                                    StageName='New'));
        }
        insert opps;
    }

    public static void setupOppsRatingClass() {

       setupCommon();
        
        accounts = new List<Account>();
        groups = new List<Billing_Group__c>();
        products = new List<Billing_Product__c>();
        
        for (Integer i=0;i<5;i++) {
            accounts.add(new Account(name='Account '+i, 
                billingcity='New York', billingcountry='USA',
                RecordTypeId=prospectRecTypeId));
        }
        insert accounts;
        
        // find the account just inserted. Add billing group and billing product for each
        for (Account account : [select id from account]) {
            Integer ratingClass = Date.today().addMonths(7).month();
  			Date renewalDate = Date.today();
            groups.add(new Billing_Group__c(Rating_Class__c=OpportunityRenewalHelper.integerToStringMonthsMap.get(ratingClass),  
                Renewal_Date__c=renewalDate, account__c=account.id, Agent_Code__c='C900'));
        }
        insert groups;

        for (Billing_Group__c grp : [select id, account__c from Billing_Group__c]) {
            products.add(new Billing_Product__c(name='Test', 
                                                Billing_Group__c =  grp.Id,
                                                Product__c=product.Id,
                                                Drug_Coverage_Code__c='008',
                                                Med_Coverage_Code__c='008',
                                                Vision_Coverage_Code__c='007'));
        }
        insert products;
    }
    
     public static void setupOppsDupsRatingClass() {

       setupCommon();
        
        accounts = new List<Account>();
        groups = new List<Billing_Group__c>();
        products = new List<Billing_Product__c>();
        
        for (Integer i=0;i<1;i++) {
            accounts.add(new Account(name='Account '+i, 
                billingcity='New York', billingcountry='USA',
                RecordTypeId=prospectRecTypeId));
        }
        insert accounts;
        
        // find the account just inserted. Add billing group and billing product for each
        for (Account account : [select id from account]) {
            Integer ratingClass = Date.today().addMonths(7).month();
  			Date renewalDate = Date.today();
            groups.add(new Billing_Group__c(Rating_Class__c=OpportunityRenewalHelper.integerToStringMonthsMap.get(ratingClass),  
                Renewal_Date__c=renewalDate.addDays(10), account__c=account.id, Agent_Code__c='C700'));
            groups.add(new Billing_Group__c(Rating_Class__c=OpportunityRenewalHelper.integerToStringMonthsMap.get(ratingClass),  
                Renewal_Date__c=renewalDate, account__c=account.id, Agent_Code__c='C800'));
            groups.add(new Billing_Group__c(Rating_Class__c=OpportunityRenewalHelper.integerToStringMonthsMap.get(ratingClass),  
                Renewal_Date__c=renewalDate.addDays(5), account__c=account.id, Agent_Code__c='C900'));
        }
        insert groups;

        for (Billing_Group__c grp : [select id, account__c from Billing_Group__c]) {
            products.add(new Billing_Product__c(name='Test', 
                                                Billing_Group__c =  grp.Id,
                                                Product__c=product.Id,
                                                Drug_Coverage_Code__c='009',
                                                Med_Coverage_Code__c='008',
                                                Vision_Coverage_Code__c='007'));
        }
        insert products;
    }

    public static void setupOppsExistRatingClass() {
        
        setupOppsRatingClass();

        opps = new  List<Opportunity>();
        Integer counter = 0;
        for (Account account : [Select Id, Name, OwnerId From Account]) {
            opps.add(new Opportunity(Name='Renewal for '+ account.Name, 
                                    CloseDate=Date.today().addMonths(-7),
                                    RecordTypeId=oppRenewalTypeId,
                                    Expected_Member_Percent__c=100,
                                    AccountId=account.Id,
                                    Initiating_Billing_Group__c=groups[counter].Id,
                                    OwnerId=account.OwnerId,
                                    StageName='Planning'));
            counter++;
        }
        insert opps;

     }

    public static void setupProposalAcceptanceOpps() {

        setupCommon();

        accounts = new List<Account>();
        opps = new  List<Opportunity>();
        oppProducts = new List<OpportunityLineItem>();

        for (Integer i=0;i<5;i++) {
            accounts.add(new Account(Name='Account '+i, 
                                    BillingCity='New York', 
                                    BillingCountry='USA',
                                    RecordTypeId=prospectRecTypeId,
                                    Funding_Type__c='Fully Insured',
                                    Funding_Mechanism__c='Community Rated Group (CRG)'));
        }
        insert accounts;


        for (Account account : [select Id, Name from account]) {
            opps.add(new Opportunity(Name='Assumptive Renewal for '+ account.Name, 
                                    CloseDate=Date.today().addDays(30),
                                    RecordTypeId=oppRecTypeId,
                                    AccountId=account.Id,
                                    Effective_Date__c=Date.today(),
                                    Effective_End_Date__c = Date.today(),
                                    Reason_for_Shopping__c='Price',
                                    Contract_Sending_Method__c='Hard Copy - Mailed by SAS',
                                    Rate_Benefit_info_with_confirmation__c='Yes',
                                    Contract_Type__c='Annual',
                                    Won_Reason__c='Network', 
                                    Employee_Count__c=3, 
                                    StageName='New'));

        }
        insert opps;

        PricebookEntry pbe = [SELECT Id, UnitPrice FROM PricebookEntry];
        for(Opportunity opp : [Select Id, Name from Opportunity]) {
           oppProducts.add(new OpportunityLineItem(UnitPrice=0.0, 
                                                PricebookEntryId=pbe.Id,
                                                OpportunityId=opp.Id,
                                                Product2Id=product.Id,
                                                Quantity=1));
        }
        insert oppProducts;
    }
    
    public static void setupAcceptanceOppsWithBillingGroup() {

        setupCommon();

        accounts = new List<Account>();
        groups = new List<Billing_Group__c>();
        opps = new  List<Opportunity>();
        oppProducts = new List<OpportunityLineItem>();

        for (Integer i=0;i<5;i++) {
            accounts.add(new Account(Name='Account '+i, 
                                    BillingCity='New York', 
                                    BillingCountry='USA',
                                    RecordTypeId=prospectRecTypeId,
                                    Funding_Type__c='Fully Insured',
                                    Funding_Mechanism__c='Community Rated Group (CRG)'));
        }
        insert accounts;
        
        for (Account account : [select id from account]) {
            Integer ratingClass = Date.today().month();
            Date renewalDate = Date.today();
            
            groups.add(new Billing_Group__c(Rating_Class__c=OpportunityRenewalHelper.integerToStringMonthsMap.get(ratingClass),  
                							Renewal_Date__c=renewalDate, 
                                            Group_Status__c='Pending',
                                            account__c=account.id, 
                                            Agent_Code__c='C900'));
        }
        insert groups;
        
        for (Account account : [select Id, Name from account]) {
            opps.add(new Opportunity(Name='Assumptive Renewal for '+ account.Name, 
                                    CloseDate=Date.today().addDays(30),
                                    RecordTypeId=oppRecTypeId,
                                    AccountId=account.Id,
                                    Effective_Date__c=Date.today(),
                                    Effective_End_Date__c = Date.today(),
                                    Reason_for_Shopping__c='Price',
                                    Contract_Sending_Method__c='Hard Copy - Mailed by SAS',
                                    Rate_Benefit_info_with_confirmation__c='Yes',
                                    Contract_Type__c='Annual',
                                    Won_Reason__c='Network', 
                                    Employee_Count__c=3, 
                                    StageName='New'));

        }
        insert opps;
        
        PricebookEntry pbe = [SELECT Id, UnitPrice FROM PricebookEntry];
        for(Opportunity opp : [Select Id, Name from Opportunity]) {
           oppProducts.add(new OpportunityLineItem(UnitPrice=0.0, 
                                                PricebookEntryId=pbe.Id,
                                                OpportunityId=opp.Id,
                                                Product2Id=product.Id,
                                                Quantity=1));
        }
        insert oppProducts;
    }

    public static void setupOppsWithBillingGroupOppProducts() {

        setupCommon();

        accounts = new List<Account>();
        groups = new List<Billing_Group__c>();
        opps = new  List<Opportunity>();
        oppProducts = new List<OpportunityLineItem>();
        grpOppProducts = new List<Billing_Group_Opp_Product__c>(); 

        for (Integer i=0;i<5;i++) {
            accounts.add(new Account(Name='Account '+i, 
                                    BillingCity='New York', 
                                    BillingCountry='USA',
                                    RecordTypeId=prospectRecTypeId,
                                    Funding_Type__c='Fully Insured',
                                    Funding_Mechanism__c='Community Rated Group (CRG)'));
        }
        insert accounts;
        
        for (Account account : [select id from account]) {
            Integer ratingClass = Date.today().month();
            Date renewalDate = Date.today();
            
            groups.add(new Billing_Group__c(Rating_Class__c=OpportunityRenewalHelper.integerToStringMonthsMap.get(ratingClass),  
                                            Renewal_Date__c=renewalDate, 
                                            Group_Status__c='Pending',
                                            account__c=account.id, 
                                            Agent_Code__c='C900'));
        }
        insert groups;
        
        for (Account account : [select Id, Name from account]) {
            opps.add(new Opportunity(Name='Assumptive Renewal for '+ account.Name, 
                                    CloseDate=Date.today().addDays(30),
                                    RecordTypeId=oppRecTypeId,
                                    AccountId=account.Id,
                                    Effective_Date__c=Date.today(),
                                    Effective_End_Date__c = Date.today(),
                                    Reason_for_Shopping__c='Price',
                                    Contract_Sending_Method__c='Hard Copy - Mailed by SAS',
                                    Rate_Benefit_info_with_confirmation__c='Yes',
                                    Contract_Type__c='Annual',
                                    Won_Reason__c='Network', 
                                    Employee_Count__c=3, 
                                    StageName='New'));

        }
        insert opps;
        
        PricebookEntry pbe = [SELECT Id, UnitPrice FROM PricebookEntry];
        for(Opportunity opp : [Select Id, Name from Opportunity]) {
           oppProducts.add(new OpportunityLineItem(UnitPrice=0.0, 
                                                PricebookEntryId=pbe.Id,
                                                OpportunityId=opp.Id,
                                                Product2Id=product.Id,
                                                Billing_Group__c=groups[0].Id,
                                                Quantity=1));
        }
        insert oppProducts;

        for(OpportunityLineItem oppItem : [Select Id, Name, OpportunityId, Billing_Group__c from OpportunityLineItem]) {
           grpOppProducts.add(new Billing_Group_Opp_Product__c(Opportunity_Product_ID__c=oppItem.Id,
                                                Opportunity__c=oppItem.OpportunityId,
                                                Billing_Group__c=oppItem.Billing_Group__c));
        }
        insert grpOppProducts;
    }
    
     public static void setupOpportunityWithMissingData(String stageName) {

        setupCommon();

        accounts = new List<Account>();
        contacts = new List<Contact>();
        groups = new List<Billing_Group__c>();
        opps = new  List<Opportunity>();
        oppProducts = new List<OpportunityLineItem>();
        grpOppProducts = new List<Billing_Group_Opp_Product__c>(); 

        for (Integer i=0;i<1;i++) {
            accounts.add(new Account(Name='Account '+i, 
                                    BillingCity='New York', 
                                    BillingCountry='USA',
                                    RecordTypeId=prospectRecTypeId,
                                    Funding_Type__c='Fully Insured',
                                    Funding_Mechanism__c='Community Rated Group (CRG)'));

            contacts.add(new Contact(FirstName='First'+i, LastName='Last'+i));
        }
        insert accounts;
        insert contacts;

        
        for (Account account : [select id from account]) {
            Integer ratingClass = Date.today().month();
            Date renewalDate = Date.today();
            
            groups.add(new Billing_Group__c(Rating_Class__c=OpportunityRenewalHelper.integerToStringMonthsMap.get(ratingClass),  
                							Renewal_Date__c=renewalDate, 
                                            Group_Status__c='Pending',
                                            Account__c=account.id, 
                                            Requested_Agent_Code__c=null, 
                         					Requested_Rating_Class__c=null,
                         					Retro_Cancellation_Allowance__c=null,
                         					Domestic_Partnership_Allowed__c=null));
        }
        insert groups;
        
        for (Account account : [select Id, Name from account]) {
            opps.add(new Opportunity(Name='Assumptive Renewal for '+ account.Name, 
                                    CloseDate=Date.today().addDays(30),
                                    RecordTypeId=oppRecTypeId,
                                    AccountId=account.Id,
                                    Employee_Count__c=3, 
                                    Effective_Date__c=Date.today(),
                                    Contract_Sending_Method__c='Hard Copy - Mailed by SAS',
                                    Rate_Benefit_info_with_confirmation__c='Yes',
                                    Won_Reason__c='Network',  
                                    Contract_Type__c='Annual', 
                                    Reason_for_Shopping__c='Price', 
                                    Effective_End_Date__c=Date.today(),
                                    GPA_Notice_Contact__c=contacts[0].Id,
                                    StageName=stageName));

        }
        insert opps;
        
        PricebookEntry pbe = [SELECT Id, UnitPrice FROM PricebookEntry];
        for(Opportunity opp : [Select Id, Name from Opportunity]) {
           oppProducts.add(new OpportunityLineItem(UnitPrice=0.0, 
                                                PricebookEntryId=pbe.Id,
                                                OpportunityId=opp.Id,
                                                Product2Id=product.Id,
                                                Billing_Group__c=groups[0].Id,   
                                                Quantity=1));
        }
        insert oppProducts;
        
        for(OpportunityLineItem oppItem : [Select Id, Name, OpportunityId, Billing_Group__c from OpportunityLineItem]) {
           grpOppProducts.add(new Billing_Group_Opp_Product__c(Opportunity_Product_ID__c=oppItem.Id,
                                                Opportunity__c=oppItem.OpportunityId,
                                                Billing_Group__c=oppItem.Billing_Group__c));
        }
        insert grpOppProducts;
         
    }
    
    public static void setupOpportunityWithCompleteData(String stageName) {

        setupCommon();

        accounts = new List<Account>();
        contacts = new List<Contact>();
        groups = new List<Billing_Group__c>();
        opps = new  List<Opportunity>();
        oppProducts = new List<OpportunityLineItem>();
        grpOppProducts = new List<Billing_Group_Opp_Product__c>(); 

        for (Integer i=0;i<1;i++) {
            accounts.add(new Account(Name='Account '+i, 
                                    BillingCity='New York', 
                                    BillingCountry='USA',
                                    RecordTypeId=customerRecTypeId,
                                    Funding_Type__c='Fully Insured',
                                    Funding_Mechanism__c='Community Rated Group (CRG)'));

            contacts.add(new Contact(FirstName='First'+i, LastName='Last'+i));
        }
        insert accounts;
        insert contacts;
        
        for (Account account : [select id from account]) {
            Integer ratingClass = Date.today().month();
            Date renewalDate = Date.today();
            
            groups.add(new Billing_Group__c(Rating_Class__c=OpportunityRenewalHelper.integerToStringMonthsMap.get(ratingClass),  
                							Renewal_Date__c=renewalDate, 
                                            Group_Status__c='Active',
                                            Account__c=account.id, 
                                            Requested_Agent_Code__c='C009', 
                         					Requested_Rating_Class__c='April',
                         					Retro_Cancellation_Allowance__c='60',
                         					Domestic_Partnership_Allowed__c='No'));
        }
        insert groups;
        //List<Billing_Group__c> groupList = [Select Id, Account__r.RecordType.DeveloperName From Billing_Group__c];
        //System.debug('###groups: '+groupList[0].Account__r.RecordType.DeveloperName);
        for (Account account : [select Id, Name from account]) {
            opps.add(new Opportunity(Name='Assumptive Renewal for '+ account.Name, 
                                    CloseDate=Date.today().addDays(30),
                                    RecordTypeId=oppRecTypeId,
                                    AccountId=account.Id,
                                    Reason_for_Shopping__c='Price',
                                    Contract_Sending_Method__c='Hard Copy - Mailed by SAS',
                                    Rate_Benefit_info_with_confirmation__c='Yes',
                                    Contract_Type__c='Annual',
                                    Won_Reason__c='Network', 
                                    Employee_Count__c=3, 
                                    Effective_Date__c=Date.today(),
                                    Effective_End_Date__c=Date.today(),
                                    GPA_Notice_Contact__c=contacts[0].Id,
                                    Send_Contract_To__c=contacts[0].Id,
                                    StageName=stageName));

        }
        insert opps;
        
        PricebookEntry pbe = [SELECT Id, UnitPrice FROM PricebookEntry];
        for(Opportunity opp : [Select Id, Name from Opportunity]) {
           oppProducts.add(new OpportunityLineItem(UnitPrice=100.0, 
                                                PricebookEntryId=pbe.Id,
                                                OpportunityId=opp.Id,
                                                Product2Id=product.Id,
                                                Billing_Group__c=groups[0].Id,   
                                                Quantity=1));
        }
        insert oppProducts;
        
        for(OpportunityLineItem oppItem : [Select Id, Name, OpportunityId,Billing_Group__c from OpportunityLineItem]) {
           grpOppProducts.add(new Billing_Group_Opp_Product__c(Opportunity_Product_ID__c=oppItem.Id,
                                                Opportunity__c=oppItem.OpportunityId,
                                                Billing_Group__c=oppItem.Billing_Group__c));
        }
        insert grpOppProducts;
         
    }
    
    public static User getTestUser() {
        Profile p = [SELECT Id FROM Profile WHERE Name='AMS Account Manager'];
        User user = new User(Alias ='testUser', 
                            Email='testuser@testorg.com',
         					EmailEncodingKey='UTF-8', 
                            LastName='Testing', 
                            LanguageLocaleKey='en_US',
         					LocaleSidKey='en_US', 
                            ProfileId=p.Id,
         					TimeZoneSidKey='America/Los_Angeles', 
                            UserName='testonic@testorg.com');
        return user;
    }
}